### PR TITLE
Give some semblence of IPC/Websocket information.

### PR DESCRIPTION
**Pull request by Sxribe**
Right now, it is really easy to get confused when the default example application (in README.md) is used and it doesn't work. This PR should add more information, so that the problem is more easily diagnosed.

### CODE REVIEW

**Comment by advaith1** [comment]
The example should use ipc, as websocket use is deprecated

**Comment by NotSugden** [comment]
https://github.com/discord/discord-api-docs/pull/1782 the `rpc.api` scope seems to have also been removed, this should also be removed from the example

**Comment by devsnek** [comment]
It is not this library's job to document discord's policy decisions.

**Comment by Sxribe** [comment]
What is the point to have an example with outdated scopes and depreciated settings? The library's job is to help developers interface with Discord's RPC. I don't see how changing the example and adding a warning to the documentation.

The information is outdated and should be fixed for future developers.

**Pull request closed without merging**
